esphome:
  name: projector
  includes:
    - uart_read_line_sensor.h
  # You need to add this file to your config/esphome directory for this to compile and work!

esp8266:
  board: d1_mini

logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

# uart set up: (may need to change these values based on your ESP32 dev board specs..
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     delimiter: "\n"
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    # ssid: "Lr Tupplur Fallback Hotspot"
    # ssid: "Br Tupplur Fallback Hotspot"
    ssid: "Epson Control Fallback Hotspot"
    password: "1234567890123"

captive_portal:

text_sensor:
# This sets up the custom sensor to read UART (required for switch status)
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline"

binary_sensor:
  # A "connected?" status sensor that - as long as sensor + mqtt + HA are working -
  #   will always display "true". Allows for easy detection of sensor failure from HA
  # See: https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: "Projector Status"
    
switch:
  - platform: template
    name: "Projector Power"
    icon: "mdi:projector"
# the lamda reads the status response defined in the interval below;
# and is used to feed back the state of the switch to Home assistant
    lambda: |-
      if (id(uart_readline).state == "PWR=01") {
        return true;
      } else if(id(uart_readline).state == "PWR=00") {
        return false;
      } else {
        return {};
      }
    turn_on_action:
      - uart.write: [0x50, 0x57, 0x52, 0x20, 0x4F, 0x4E, 0x0D] # PWR ON\r
    turn_off_action:
      - uart.write: [0x50, 0x57, 0x52, 0x20, 0x4F, 0x46, 0x46, 0x0D] # PWR OFF\r

interval:
# I set this up for 20 seconds as the Optoma projector seems to get a 
# bit confused when too many commands come in at once - and stops accepting
# remote (IR) and Serial commands until the power is reset.
# setting this for 20s reduces the chance of overlapping commands being sent
# when sennding power on/ off commands from home assistant.
  - interval: 10s
    then:
      - uart.write: [0x50, 0x57, 0x52, 0x3F, 0x0D] # PWR?\r
      - delay: 1s















